<?php
/**
 * WordPress Configuration File
 *
 * This file contains universal settings and loads environment-specific
 * configuration. Safe for version control.
 *
 * Environment files (gitignored):
 * - wp-config-ddev.php : Auto-generated by DDEV for local macOS development
 * - wp-config-env.php  : Create this on each server (Linux dev, Linode production)
 *
 * @package awakeningprisonart
 */

/** Absolute path to the WordPress directory. */
defined( 'ABSPATH' ) || define( 'ABSPATH', dirname( __FILE__ ) . '/' );

/**
 * Load environment-specific configuration.
 *
 * Priority:
 * 1. DDEV (detected via IS_DDEV_PROJECT environment variable)
 * 2. wp-config-env.php (for Linux server, Linode, or any other environment)
 */
if ( getenv( 'IS_DDEV_PROJECT' ) === 'true' && file_exists( __DIR__ . '/wp-config-ddev.php' ) ) {
	// DDEV local development.
	require_once __DIR__ . '/wp-config-ddev.php';
} elseif ( file_exists( __DIR__ . '/wp-config-env.php' ) ) {
	// Server-specific configuration (Linux dev, Linode production, etc.).
	require_once __DIR__ . '/wp-config-env.php';
} else {
	// No environment config found - this will cause WordPress to fail gracefully.
	die( 'Error: No environment configuration found. Please create wp-config-env.php for this server.' );
}

/**
 * Universal Settings
 * These apply to all environments.
 */

/** Database charset to use in creating database tables. */
defined( 'DB_CHARSET' ) || define( 'DB_CHARSET', 'utf8mb4' );

/** The database collate type. Don't change this if in doubt. */
defined( 'DB_COLLATE' ) || define( 'DB_COLLATE', '' );

/**
 * WordPress Database Table prefix.
 * Can be overridden in environment config.
 */
if ( ! isset( $table_prefix ) || empty( $table_prefix ) ) {
	$table_prefix = 'wp_';
}

/* Add any custom values between this line and the "stop editing" line. */



/* That's all, stop editing! Happy publishing. */

/** Include wp-settings.php */
if ( file_exists( ABSPATH . '/wp-settings.php' ) ) {
	require_once ABSPATH . '/wp-settings.php';
}
